# Generated by Django 3.0.3 on 2020-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batch_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='未知', max_length=255),
        ),
    ]
